#%RAML 0.8
title: HacksummitAPI
version: v1
baseUri: http://hacksummit.apptension.com
mediaType:  application/json
schemas:
  - User: !include schemas/user.json
  - Project: !include schemas/project.json
  - Skill: !include schemas/skill.json
  - Evaluation: !include schemas/evaluation.json
  - Role: !include schemas/role.json
/user:
  get:
    description: Return the list of the users
    responses:
      200:
        body:
          application/json:
            example: !include examples/users.json
  /me:
    get:
      description: Returns current logged user
      responses:
        200:
          body:
            application/json:
              schema: User
  /logout:
    post:
      description: Log out current user
      responses:
        200:
          body:
            application/json:
              example: |
                { "success": true }
  /login:
    post:
      description: Loggin user with a given id
      body:
        application/json:
          example: |
            { "userId": 1 }
      responses:
        200:
          body:
            application/json:
              example: |
                { "success": true }

  /{id}:
    uriParameters:
      id:
        type: integer
    get:
      description: Get single user
      responses:
        200:
          body:
            application/json:
              schema: User
    /role:
      get:
        description: list all user roles
        responses:
          200:
            body:
              application/json:
                example: !include examples/roles.json
      post:
        description: sets user roles
        body:
          application/json:
            schema: !include schemas/roles_assign_post.json
        responses:
          200:
            body:
              application/json:
                example: |
                  { "success": true }

    /evaluation:
      get:
        description: return latest evaluation
        responses:
          200:
            body:
              application/json:
                schema: Evaluation
      put:
        description: update the evaluation
        body:
          application/json:
            formParameters:
              evaluationId:
                description: Id of previously received evaluation.
                type: integer
              state:
                description: Rating status. 0 = pending, 1 = answered, 2 = skipped (dismiss). Optional if rating is not dismissed.
                type: integer
              starred:
                description: Rating value. 0 = zero, 1 = plus one. Optional if rating is dismissed.
                type: integer
              comment:
                description: Optional comment.
                type: string
        responses:
          200:
            body:
              application/json:
                example: |
                  {
                    "success": true
                  }

/project:
  get:
    description: Returns list of the projects
    responses:
      200:
        body:
          application/json:
            example: !include examples/projects.json
  post:
    description: Add new project
    body:
      application/json:
        schema: Project
    responses:
      200:
        body:
          application/json:
            schema: Project
  /{id}:
    uriParameters:
      id:
        type: integer
    get:
      description: Get single project
      responses:
        200:
          body:
            application/json:
              schema: Project
    put:
      description: Update project
      body:
        application/json:
          schema: Project
      responses:
        200:
          body:
            application/json:
              schema: Project
    delete:
      description: Remove project
      responses:
        204:
          description: No content

/skill:
  get:
    description: Returns list of the skills
    responses:
      200:
        body:
          application/json:
            example: !include examples/skills.json
  post:
    description: Add new skill
    body:
      application/json:
        schema: Skill
    responses:
      200:
        body:
          application/json:
            schema: Skill
  /{id}:
    uriParameters:
      id:
        type: integer
    get:
      description: Get single skill
      responses:
        200:
          body:
            application/json:
              schema: Skill
    put:
      description: Update skill
      body:
        application/json:
          schema: Skill
      responses:
        200:
          body:
            application/json:
              schema: Skill
    delete:
      description: Remove skill
      responses:
        204:
          description: No content

/role:
  get:
    description: Returns list of roles
    responses:
      200:
        body:
          application/json:
            example: !include examples/roles.json
  post:
    description: Add new role
    body:
      application/json:
        schema: Role
    responses:
      200:
        body:
          application/json:
            schema: Role
  /{id}:
    uriParameters:
      id:
        type: integer
    get:
      description: Get single role
      responses:
        200:
          body:
            application/json:
              schema: Role
    put:
      description: Update role
      body:
        application/json:
          schema: Role
      responses:
        200:
          body:
            application/json:
              schema: Role
    delete:
      description: Remove role
      responses:
        204:
          description: No content
    # /skill:
    #   get:
    #     description: return skills assigned to role
    #     responses:
    #       200:
    #         body:
    #           application/json:
    #             example: !include examples/skills.json
    #   post:
    #     description: assign skills to role
    #     body:
    #       application/json:
    #         schema: !include schemas/skills_assign_post.json
    #     responses:
    #       200:
    #         body:
    #           application/json:
    #             example: !include examples/skills.json

/evaluation:
  get:
    description: Returns list of evaluations
    responses:
      200:
        body:
          application/json:
            example: !include examples/evaluations.json
  /date/{date}:
    uriParameters:
      date:
        type: integer
    get:
      description: Returns list of evaluations for the given date
      responses:
        200:
          body:
            application/json:
              schema: Evaluation

/stat:
  get:
    description: Returns stats for given user
    queryParameters:
      startDate:
        type: date
      endDate:
        type: date
      user:
      project:
      skill:

    responses:
      200:
        body:
          application/json:
            example: !include ./examples/stats.json
